### ISSUE TITLE
fix css

### ISSUE THREAD

**Issue by rizuwan86** [rizuwan86/dcbot_tx#13]
```css
.d #ct-wrap.ct-user-wrap .map-overview .grid-layer {
    top: 65px !important;
}
```
to
```css
.d #ct-wrap.ct-user-wrap .map-overview .grid-layer {
    top: 87px !important;
}
```
